name: build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x]

        steps:
            - uses: actions/checkout@v3

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 8.5.1

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm run build
